Re-enable tests in %check
Upstream <https://git.libreoffice.org/core/+/
a58e086ededb8442938e81f971dfae36ef7eb076%5E!> "rework the default make target"
towards libreoffice-7-0 had dropped the unitcheck and slowcheck targets from the
default target.

But after the preceding b27571d6882b8436db9d5284a876b54569ea7a32 "Enable LTO
again", that reveals that there appears to still be issues with LTO at least on
i686, which fails with

> ### unexpected exception content! failed
> ### unexpected exception content! failed
> ### unexpected exception content! failed
> exception test failed
> oneway exception test failed
> exception occurred: error: test failed! /builddir/build/BUILD/libreoffice-7.0.0.3/testtools/source/bridgetest/bridgetest.cxx:1176
> > error: error: test failed! /builddir/build/BUILD/libreoffice-7.0.0.3/testtools/source/bridgetest/bridgetest.cxx:1176
> > dying...make[1]: *** [/builddir/build/BUILD/libreoffice-7.0.0.3/testtools/CustomTarget_uno_test.mk:25: /builddir/build/BUILD/libreoffice-7.0.0.3/workdir/CustomTarget/testtools/uno_test.done] Error 1

(<https://koji.fedoraproject.org/koji/getfile?taskID=49136895&volume=DEFAULT
&name=build.log&offset=-4000>), so keep LTO disabled there until the issue is
addressed.

Note that for aarch64, armv7hl, and s390x %check is currently no-op, so it is
not obvious from just building the package whether or not they will have issues
with LTO at runtime.  But at least for ppc64le and x86_64 the (non--no-op)
%check has been seen to succeed with LTO enabled, including the
CppunitTest_sw_apitests for which LTO had originally been disabled for LO 6.4 in
5d644f1606b76ffa4a102433849a824d7293a404 "%check fails with lto enabled" (see
<https://koji.fedoraproject.org/koji/taskinfo?taskID=49136767>).