The __pycache__ files are generated by a Flatpak build now after all
> Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/libreoffice-6.4.7.2-4.module+f32+2+48ebc82b.x86_64
> error: Installed (but unpackaged) file(s) found:
>    /app/lib64/python3.8/site-packages/__pycache__/officehelper.cpython-38.opt-1.pyc
>    /app/lib64/python3.8/site-packages/__pycache__/officehelper.cpython-38.pyc
>    /app/lib64/python3.8/site-packages/__pycache__/uno.cpython-38.opt-1.pyc
>    /app/lib64/python3.8/site-packages/__pycache__/uno.cpython-38.pyc
>    /app/lib64/python3.8/site-packages/__pycache__/unohelper.cpython-38.opt-1.pyc
>    /app/lib64/python3.8/site-packages/__pycache__/unohelper.cpython-38.pyc

(cherry picked from commit 3d414dbcfcc3fed5255ef915ba05a73b9b28f78e)