Don't strip -g from RPM_OPT_FLAGS
Missing -g trips over debuginfo generation after latest rpm changes
(only on s390x though, for reasons unknown):

error: Empty %files file /builddir/build/BUILD/libreoffice-5.4.0.3/debugsourcefiles.list